In [4]:
# %pip install pandas

import pandas as pd

data = {
    "Student_id":["S101","S102","S103","S104","S105","S106"],
    "Name":["Rahul","Nishant","Riya","Amit","Payal","Neelam"],
    "Course":["Python","Java","SQL","GO","C++","JSP"],
    "City":["Delhi","Mumbai","Pune","Delhi","Jaipur","Surat"],
    "Marks":[45,34,90,56,78,77]
}

students = pd.DataFrame(data)
students

  Student_id     Name  Course    City  Marks
0       S101    Rahul  Python   Delhi     45
1       S102  Nishant    Java  Mumbai     34
2       S103     Riya     SQL    Pune     90
3       S104     Amit      GO   Delhi     56
4       S105    Payal     C++  Jaipur     78
5       S106   Neelam     JSP   Surat     77

In [5]:
#check index 
print(students.index)

RangeIndex(start=0, stop=6, step=1)

In [6]:
# access data from index 
# loc[indexnumber]
print(students.loc[1])

Student_id       S102
Name          Nishant
Course           Java
City           Mumbai
Marks              34
Name: 1, dtype: object

In [7]:
# set index - Student_id
# custom index
students = students.set_index("Student_id")
students

               Name  Course    City  Marks
Student_id
S101          Rahul  Python   Delhi     45
S102        Nishant    Java  Mumbai     34
S103           Riya     SQL    Pune     90
S104           Amit      GO   Delhi     56
S105          Payal     C++  Jaipur     78
S106         Neelam     JSP   Surat     77

In [8]:
# access data row from custom index 
# loc[]
print(students.loc["S102"])

Name      Nishant
Course       Java
City       Mumbai
Marks          34
Name: S102, dtype: object

In [10]:
# Multiple index labels

print(students.loc[["S102","S106"]])

               Name Course    City  Marks
Student_id
S102        Nishant   Java  Mumbai     34
S106         Neelam    JSP   Surat     77

In [11]:
# series index 

marks = pd.Series(
    [85,92,78],
    index=["S101","S102","S103"]
)
marks

S101    85
S102    92
S103    78
dtype: int64

In [12]:
# access series index 
print(marks.index)

Index(['S101', 'S102', 'S103'], dtype='str')

In [13]:
print(marks.index[0])

S101

In [14]:
marks.index[0] = "S999"

TypeError: Index does not support mutable operations

In [15]:
# Replace complete index
marks.index = ["A","B","C"]
print(marks)

A    85
B    92
C    78
dtype: int64

In [16]:
# DataFrame Column index

print(students.columns)

Index(['Name', 'Course', 'City', 'Marks'], dtype='str')

In [18]:
# check whether columns exists

print("Marks" in students.columns)

True

In [19]:
print("Salary" in students.columns)

False

In [20]:
# duplicate index 
students_dup = pd.DataFrame(
    {
        "Name":["Rahul","Nishant","Neelam","Amit"],
        "Marks":[67,89,66,50]
    },
    index=["S101","S102","S102","S103"]
)

students_dup

         Name  Marks
S101    Rahul     67
S102  Nishant     89
S102   Neelam     66
S103     Amit     50

In [21]:
# select duplicate index 
print(students_dup.loc["S102"])

         Name  Marks
S102  Nishant     89
S102   Neelam     66

In [23]:
# is_unique

print(students_dup.index.is_unique)

False

In [24]:
print(students.index.is_unique)

True

In [36]:
# is_monotonic_increasing -
# is_monotonic_decreasing - 

s = pd.Series([10,8,7,6,5,5])
# print(s)
print(s.is_monotonic_increasing)
print(s.is_monotonic_decreasing)

False
True

In [37]:
# unique() 

course = pd.Index(students["Course"])
course

Index(['Python', 'Java', 'SQL', 'GO', 'C++', 'JSP'], dtype='str', name='Course')

In [38]:
print(course.unique())

Index(['Python', 'Java', 'SQL', 'GO', 'C++', 'JSP'], dtype='str', name='Course')

In [39]:
# isin()
print(students["Course"].isin(["Python","Java"]))

Student_id
S101     True
S102     True
S103    False
S104    False
S105    False
S106    False
Name: Course, dtype: bool

In [40]:
python_java_students = students[
    students["Course"].isin(["Python","Java"])
]

python_java_students

               Name  Course    City  Marks
Student_id
S101          Rahul  Python   Delhi     45
S102        Nishant    Java  Mumbai     34