In [1]:
import pandas as pd

In [3]:
data = {
    'Name':['Rohan','Naresh','Rahul','Aditi','Ganesh'],
    'Age':[23,34,25,16,70],
    'City':['Mumbai','Pune','Jaipur','Bhuj','Surat'],
}

df = pd.DataFrame(data)
df

     Name  Age    City
0   Rohan   23  Mumbai
1  Naresh   34    Pune
2   Rahul   25  Jaipur
3   Aditi   16    Bhuj
4  Ganesh   70   Surat

In [5]:
data = [
    ['Rohan','Naresh','Rahul','Aditi','Ganesh'],
    [23,34,25,16,70],
    ['Mumbai','Pune','Jaipur','Bhuj','Surat'],
]

df2 = pd.DataFrame(data)
df2

        0       1       2      3       4
0   Rohan  Naresh   Rahul  Aditi  Ganesh
1      23      34      25     16      70
2  Mumbai    Pune  Jaipur   Bhuj   Surat

In [6]:
col = ['Student1','Student2','Student3','Student4','Student5']
df3 = pd.DataFrame(data,columns=col)
df3

  Student1 Student2 Student3 Student4 Student5
0    Rohan   Naresh    Rahul    Aditi   Ganesh
1       23       34       25       16       70
2   Mumbai     Pune   Jaipur     Bhuj    Surat

In [8]:
# export CSV
df3.to_csv('Student_info.csv',index=False)

In [10]:
# read csv file 
data = pd.read_csv("credit_card_transactions.csv")

In [12]:
# load top 5 record 
data.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452.0,2023-01-01,NaN,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775.0,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,NaN
2,100002,2259.0,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545.0,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137.0,2023-01-01,ATM,NaN,Travel,2517.07,Debit Card,Approved,Matthewland

In [13]:
data.head(3)

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452.0,2023-01-01,NaN,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775.0,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,NaN
2,100002,2259.0,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James

In [14]:
# last 5 record
data.tail()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
16495,TXN116495,CUST60769,2023-03-11,Online,BestBuy,Electronics,13681.52,UPI,Approved,West Kiara
16496,TXN116496,CUST64670,2023-05-10,ATM,Uber,Clothing,34951.01,PayPal,Approved,West Bruceport
16497,TXN116497,CUST55544,NaN,Mobile Payment,Netflix,Travel,26960.87,Debit Card,NaN,Robertmouth
16498,TXN116498,CUST53365,2023-04-11,POS,Apple Store,Groceries,31842.40,Credit Card,Pending,Lake Edwardchester
16499,TXN116499,CUST99692,2023-08-17,Online,Amazon,Travel,21091.60,Debit Card,Approved,Kleinhaven

In [16]:
# size of data set 
data.shape

(16500, 10)

In [18]:
# check columns name 
data.columns.to_list()

['Transaction_ID',
 'Customer_ID',
 'Transaction_Date',
 'Transaction_Type',
 'Merchant',
 'Category',
 'Amount',
 'Payment_Mode',
 'Transaction_Status',
 'Location']

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 16500 entries, 0 to 16499
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      16500 non-null  str
 1   Customer_ID         15167 non-null  str
 2   Transaction_Date    15131 non-null  str
 3   Transaction_Type    15132 non-null  str
 4   Merchant            15158 non-null  str
 5   Category            15144 non-null  str
 6   Amount              15100 non-null  float64
 7   Payment_Mode        15184 non-null  str
 8   Transaction_Status  15128 non-null  str
 9   Location            15175 non-null  str
dtypes: float64(1), str(9)
memory usage: 1.3 MB

In [20]:
# numeric summary 
data.describe()

             Amount
count  15100.000000
mean   16208.393093
std    15819.878614
min        6.550000
25%     2764.082500
50%     8788.420000
75%    29613.212500
max    49998.010000

In [ ]:
data[['Amount','Category','Payment_Mode']].head()

    Amount  Category Payment_Mode
0  4520.70    Travel   Debit Card
1  1437.85    Travel   Debit Card
2  3320.52  Clothing       PayPal
3  2659.96    Travel   Debit Card
4  2517.07    Travel   Debit Card