In [ ]:
import pandas as pd
# melt() 

# example :- 
wide_df = pd.DataFrame(
    {
        'store':['North','South','East'],
        '2021':[1200,800,900],
        '2022':[1500,900,1100],
        '2023':[1400,850,1000]    
    }
)

wide_df

store | year |  sales
North | 2021 |  1200

In [17]:
# unpivot pd.melt()
long_df = pd.melt(
    wide_df, # data
    id_vars=['store'], # columns
    value_vars=['2021','2022'], # column to melt
    var_name='year', # new col
    value_name='sales' # new col    
)

long_df

   store  year  sales
0  North  2021   1200
1  South  2021    800
2   East  2021    900
3  North  2022   1500
4  South  2022    900
5   East  2022   1100

In [ ]:
long_df.to_csv("data.csv")

In [14]:
data = pd.DataFrame(
    {
        'store':['North','South','East'],
        'Product':['Laptop','Mouse','Keybord'],
        '2021':[1200,800,900],
        '2022':[1500,900,1100],
        '2023':[1400,850,1000],
        'price_day1':[120,450,650],
        'price_day2':[560,890,780]   
    }
)

In [ ]:
# store |Product | year | price

In [13]:
# melt all
long_all = pd.melt(
    wide_df,
    id_vars=['store'],
    var_name='year',
    value_name='sales'
    )

long_all

   store  year  sales
0  North  2021   1200
1  South  2021    800
2   East  2021    900
3  North  2022   1500
4  South  2022    900
5   East  2022   1100
6  North  2023   1400
7  South  2023    850
8   East  2023   1000

In [16]:
long_all1 = pd.melt(
    data,
    id_vars=['Product'],
    var_name='year',
    value_name='sales'
    )

long_all1

    Product        year  sales
0    Laptop       store  North
1     Mouse       store  South
2   Keybord       store   East
3    Laptop        2021   1200
4     Mouse        2021    800
5   Keybord        2021    900
6    Laptop        2022   1500
7     Mouse        2022    900
8   Keybord        2022   1100
9    Laptop        2023   1400
10    Mouse        2023    850
11  Keybord        2023   1000
12   Laptop  price_day1    120
13    Mouse  price_day1    450
14  Keybord  price_day1    650
15   Laptop  price_day2    560
16    Mouse  price_day2    890
17  Keybord  price_day2    780

In [ ]:
wide_df['Manager'] = ['rupali','joy','ashok']

long_df = pd.melt(
    wide_df, # data
    id_vars=['store','Manager'], # columns
    value_vars=['2021','2022','2023'], # column to melt
    var_name='year', # new col
    value_name='sales' # new col    
)

long_df

   store Manager  year  sales
0  North  rupali  2021   1200
1  South     joy  2021    800
2   East   ashok  2021    900
3  North  rupali  2022   1500
4  South     joy  2022    900
5   East   ashok  2022   1100
6  North  rupali  2023   1400
7  South     joy  2023    850
8   East   ashok  2023   1000

In [ ]:
scores_wide = pd.DataFrame({
    'Student': ['Ali', 'Beth', 'Cathy'],
    'Math': [85, 90, 78],
    'Science': [88, 92, 80],
    'English': [90, 85, 88]
})

scores_wide

# output :- 
# Student | Subject | Score
# average score per subjects

  Student  Math  Science  English
0     Ali    85       88       90
1    Beth    90       92       85
2   Cathy    78       80       88