In [1]:
import pandas as pd

data = {
    'Name':['Nishant','Joy','Sejal','Aryan','Anita','Ayushi'],
    'Age':[12,13,14,15,16,17],
    'City':['Mumbai','Pune','Goa','Jaipur','bhuj','Surat']
}

df = pd.DataFrame(data)
df

      Name  Age    City
0  Nishant   12  Mumbai
1      Joy   13    Pune
2    Sejal   14     Goa
3    Aryan   15  Jaipur
4    Anita   16    bhuj
5   Ayushi   17   Surat

In [2]:
# print top 2 record 
df.head(2)

      Name  Age    City
0  Nishant   12  Mumbai
1      Joy   13    Pune

In [3]:
# print top 5 
df.head()

      Name  Age    City
0  Nishant   12  Mumbai
1      Joy   13    Pune
2    Sejal   14     Goa
3    Aryan   15  Jaipur
4    Anita   16    bhuj

In [4]:
# print last 5 
df.tail(2)

     Name  Age   City
4   Anita   16   bhuj
5  Ayushi   17  Surat

In [5]:
# print info 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [6]:
# numeric summary 
df.describe()

             Age
count   6.000000
mean   14.500000
std     1.870829
min    12.000000
25%    13.250000
50%    14.500000
75%    15.750000
max    17.000000

In [7]:
# datatype 
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [8]:
# create shape 
df.shape

(6, 3)

In [9]:
# print all columns name 
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [10]:
# print single columns data 
print(df['Name'])

0    Nishant
1        Joy
2      Sejal
3      Aryan
4      Anita
5     Ayushi
Name: Name, dtype: object

In [11]:
# print 2 columns
print(df[['Age','Name']])

   Age     Name
0   12  Nishant
1   13      Joy
2   14    Sejal
3   15    Aryan
4   16    Anita
5   17   Ayushi

In [12]:
# rows 
df.iloc[1] # by position

Name     Joy
Age       13
City    Pune
Name: 1, dtype: object

In [13]:
# label 
df.loc[1] # default index

Name     Joy
Age       13
City    Pune
Name: 1, dtype: object

In [14]:
# slice row 
df.iloc[1:3]

    Name  Age  City
1    Joy   13  Pune
2  Sejal   14   Goa

In [15]:
# add new columns 
df['Salary'] = [23000,78000,89000,67000,56000,90000]
df

      Name  Age    City  Salary
0  Nishant   12  Mumbai   23000
1      Joy   13    Pune   78000
2    Sejal   14     Goa   89000
3    Aryan   15  Jaipur   67000
4    Anita   16    bhuj   56000
5   Ayushi   17   Surat   90000

In [16]:
# basic Statistics 
# print average age 
print(df['Age'].mean())

14.5

In [17]:
# max salary 
print(df['Salary'].max())

90000

In [18]:
# total salary 
print(df['Salary'].sum())

403000

In [19]:
# export CSV
df.to_csv("data.csv")