In [3]:
# Data Exploration and Cleaning
# Load the dataset into a Pandas DataFrame and display the first 5 rows.
# Check the shape, column names, and summary statistics of the dataset.
# Identify and handle missing values (fill or drop based on the data type).
# Convert Transaction_Date into datetime format and extract year, month, and day as new columns.

In [4]:
# Load the dataset into a Pandas DataFrame and display the first 5 rows.
import pandas as pd

df = pd.read_csv("cc.csv")
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [5]:
# Check the shape, column names, and summary statistics of the dataset.
print(df.shape) #(row,col)
print(df.columns.to_list())
print('summary statistics \n ',df.describe()) # include='all'

(5500, 10)
['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Transaction_Type', 'Merchant', 'Category', 'Amount', 'Payment_Mode', 'Transaction_Status', 'Location']
summary statistics
         Transaction_ID  Customer_ID       Amount
count     5500.000000  5500.000000  5490.000000
mean    102749.500000  2989.954182  2491.062299
std       1587.857571  1153.928878  1444.542432
min     100000.000000  1000.000000     6.550000
25%     101374.750000  1988.000000  1236.402500
50%     102749.500000  3000.000000  2502.405000
75%     104124.250000  3990.000000  3765.420000
max     105499.000000  4998.000000  4997.490000

In [6]:
#check dtype
df.dtypes

Transaction_ID          int64
Customer_ID             int64
Transaction_Date       object
Transaction_Type       object
Merchant               object
Category               object
Amount                float64
Payment_Mode           object
Transaction_Status     object
Location               object
dtype: object

In [7]:
# Identify and handle missing values (fill or drop based on the data type).
print(df.isnull().sum())
# Convert Transaction_Date into datetime format and extract year, month, and day as new columns.

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Transaction_Type       1
Merchant               2
Category               5
Amount                10
Payment_Mode           3
Transaction_Status     2
Location               0
dtype: int64

In [8]:
# fill the missing value 
df['Merchant'] = df['Merchant'].fillna('Unknown')
df['Transaction_Type'] = df['Transaction_Type'].fillna('Unknown')
df['Category'] = df['Category'].fillna('Unknown')
df['Payment_Mode'] = df['Payment_Mode'].fillna('Unknown')
df['Transaction_Status'] = df['Transaction_Status'].fillna('Unknown')

# fill int values
df['Amount'] = df['Amount'].fillna(df['Amount'].median()) # mean()
print(df.isnull().sum())

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64

In [9]:
df.dtypes

Transaction_ID          int64
Customer_ID             int64
Transaction_Date       object
Transaction_Type       object
Merchant               object
Category               object
Amount                float64
Payment_Mode           object
Transaction_Status     object
Location               object
dtype: object

In [10]:
# Convert Transaction_Date into datetime format and extract year, month, and day as new columns.

df.dtypes

Transaction_ID          int64
Customer_ID             int64
Transaction_Date       object
Transaction_Type       object
Merchant               object
Category               object
Amount                float64
Payment_Mode           object
Transaction_Status     object
Location               object
dtype: object

In [11]:
df['Transaction_Date']  = pd.to_datetime(df['Transaction_Date'],errors='coerce')
print(df.dtypes)

Transaction_ID                 int64
Customer_ID                    int64
Transaction_Date      datetime64[ns]
Transaction_Type              object
Merchant                      object
Category                      object
Amount                       float64
Payment_Mode                  object
Transaction_Status            object
Location                      object
dtype: object

In [12]:
#  year, month, and day as new columns
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Day'] = df['Transaction_Date'].dt.day

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      5500 non-null   int64
 1   Customer_ID         5500 non-null   int64
 2   Transaction_Date    5500 non-null   datetime64[ns]
 3   Transaction_Type    5500 non-null   object
 4   Merchant            5500 non-null   object
 5   Category            5500 non-null   object
 6   Amount              5500 non-null   float64
 7   Payment_Mode        5500 non-null   object
 8   Transaction_Status  5500 non-null   object
 9   Location            5500 non-null   object
 10  Year                5500 non-null   int32
 11  Month               5500 non-null   int32
 12  Day                 5500 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(3), int64(2), object(6)
memory usage: 494.3+ KB
None

In [13]:
df.head()
df.to_csv("clean_data.csv")

In [14]:
# Data Selection and Indexing
# Retrieve all transactions made in January 2024.
# Find transactions where Amount > 1000 and Transaction_Type is "Online".
# Select only Approved transactions from the dataset.
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1

In [15]:
# # Retrieve all transactions made in January 2023.
jan_24 = df[(df['Year'] == 2023) & ( df['Month'] == 1)] 
# print(jan_24.count())
jan_24.to_csv("jan_24.csv",index=False)

In [16]:
# Q1 - Find transactions where Amount > 3000 and Transaction_Type is "Online".
high_transactions = df[(df['Amount'] > 3000) & (df['Transaction_Type'] == "Online")]
high_transactions.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1
22,100022,3057,2023-01-01,Online,BestBuy,Groceries,4094.49,PayPal,Approved,West Kenneth,2023,1,1
26,100026,4254,2023-01-02,Online,BestBuy,Travel,4054.78,Credit Card,Approved,Stevensmouth,2023,1,2
27,100027,1719,2023-01-02,Online,Walmart,Entertainment,4471.68,UPI,Pending,Riveramouth,2023,1,2
34,100034,2424,2023-01-02,Online,Target,Groceries,4074.73,PayPal,Approved,North Marytown,2023,1,2

In [17]:
# Q2 - Select only Approved transactions from the dataset.
approved_transactions = df[df['Transaction_Status'] == 'Approved']
approved_transactions.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1

In [18]:
# Data Manipulation and Feature Engineering
# Create a new column Discounted_Amount, assuming a 5% discount on all transactions above $4500.
df['Discounted_Amount'] = df['Amount'].apply(lambda x : x * 0.95 if x > 4500 else x)
df[['Amount','Discounted_Amount']].head()

    Amount  Discounted_Amount
0  4520.70           4294.665
1  1437.85           1437.850
2  3320.52           3320.520
3  2659.96           2659.960
4  2517.07           2517.070

In [19]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day,Discounted_Amount
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1,4294.665
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1,1437.850
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1,3320.520
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1,2659.960
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1,2517.070

In [20]:
# Categorize the Transaction_Amount into Low, Medium, and High based on:
# Low: Below $2000
# Medium: Between $2000 - $4500
# High: Above $4500

df['Amount_Category'] = pd.cut(df['Amount'],
                               bins=[-float('inf'),2000,4500,float('inf')],
                               labels=['Low','Medium','High'])

df[['Amount','Amount_Category']].head()

# Drop the Merchant column if more than 30% of values are missing.
missing_value = df['Merchant'].isnull().mean()
print(missing_value)

if missing_value > 0.3:
    df.drop(columns=['Merchant'],inplace=True)
    print("Delete done ...")
else:
    print("no missing value found...")

0.0
no missing value found...

In [21]:
# Aggregation and Insights
# Find the total transaction amount per Category.
total_amount_per_category = df.groupby('Category')['Amount'].sum().reset_index()
total_amount_per_category

        Category       Amount
0       Clothing  2183340.875
1         Dining  2400761.790
2    Electronics  2312580.580
3  Entertainment  2245125.780
4      Groceries  2379876.120
5         Travel  2168738.345
6        Unknown    10532.580

In [22]:
# Determine the number of declined transactions per Payment_Mode.
decliend_transactions = df[df['Transaction_Status']=='Declined'].groupby('Payment_Mode').size().reset_index(name='declined_count')
decliend_transactions

  Payment_Mode  declined_count
0  Credit Card             117
1   Debit Card             145
2       PayPal             135
3          UPI             134

In [23]:
# Find the average transaction amount per Location.
avg_amount_loc = df.groupby('Location')['Amount'].mean().reset_index()
avg_amount_loc

          Location    Amount
0        Aaronfort  2429.860
1       Aaronmouth  2648.060
2        Aaronside   315.540
3       Abbottbury  1549.850
4      Abigailfort  3634.880
...            ...       ...
4658  Zacharyburgh  2430.690
4659  Zacharyhaven   830.360
4660  Zacharymouth  3508.690
4661   Zacharystad  2925.135
4662   Zavalaburgh   364.530

[4663 rows x 2 columns]

In [24]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day,Discounted_Amount,Amount_Category
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1,4294.665,High
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1,1437.850,Low
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1,3320.520,Medium
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1,2659.960,Medium
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1,2517.070,Medium

In [25]:
# Identify the top 5 most frequent merchants based on transaction count (Amount).
top_merchants = df['Merchant'].value_counts().head(5).reset_index()
top_merchants

  Merchant  count
0     Uber    833
1  Walmart    818
2  BestBuy    790
3  Netflix    774
4   Amazon    769

In [33]:
# load customer info CSV.

customer_info = pd.read_csv("customer_info.csv")
# customer_info.tail()

In [32]:
merged_df = pd.merge(df,customer_info,on='Customer_ID' , how='inner')
merged_df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Day,Discounted_Amount,Amount_Category,Age,Gender,Membership_Level
0,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1,1437.85,Low,46,Male,Silver
1,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1,3320.52,Medium,18,Female,Gold
2,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1,2517.07,Medium,48,Male,Silver
3,100006,1587,2023-01-01,Online,Netflix,Entertainment,2309.06,Debit Card,Approved,Scottport,2023,1,1,2309.06,Medium,36,Female,Platinum
4,100007,2103,2023-01-01,ATM,Uber,Dining,334.82,PayPal,Pending,Shawview,2023,1,1,334.82,Low,29,Male,Silver

In [42]:
# Find the average transaction amount per Age group.
age_bin = [0,18,30,50,100]
age_labels = ['<18','18-30','30-50','>50']

merged_df['Age_Group'] = pd.cut(merged_df['Age'],bins=age_bin,labels=age_labels,include_lowest=True)
avg_amount_per_age_group = merged_df.groupby('Age_Group')['Amount'].mean().reset_index()
avg_amount_per_age_group

C:\Users\Admin\AppData\Local\Temp\ipykernel_4392\890989498.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_amount_per_age_group = merged_df.groupby('Age_Group')['Amount'].mean().reset_index()

  Age_Group       Amount
0       <18  2746.317647
1     18-30  2437.124325
2     30-50  2491.450375
3       >50  2524.298427